
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def main(limit):
    sum = 0
    temp = 1
    add = 1
    while sum < limit:
        temp = temp + add
        add = temp - add

        if temp % 2 == 0:
            sum = sum + temp

    return(sum)

print(main(4000000))

        

